-- CreateEnum
CREATE TYPE "DreGroup" AS ENUM ('RECEITA_BRUTA', 'DEDUCOES_RECEITA', 'CUSTO_VARIAVEL', 'DESPESA_PESSOAL', 'DESPESA_ADMINISTRATIVA', 'DESPESA_COMERCIAL', 'DESPESA_PRODUTIVA', 'RESULTADO_FINANCEIRO_RECEITA', 'RESULTADO_FINANCEIRO_DESPESA', 'NAO_OPERACIONAL_RECEITA', 'NAO_OPERACIONAL_DESPESA');

-- AlterTable
ALTER TABLE "categories" ADD COLUMN     "dreGroup" "DreGroup";
